webtalk_init -webtalk_dir C:/JAEWOO_SoC/Vivado_2019/basys3_soc_24/basys3_soc_24.sim/sim_1/behav/xsim/xsim.dir/bcd_updowncounter_p_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 12 15:41:59 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8b23a149-e8c9-48de-b0d6-a2aeca4e15c5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c63283ba217c4de3a761ea6b2bb28127" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1480 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 291078757 -regid "" -xml C:/JAEWOO_SoC/Vivado_2019/basys3_soc_24/basys3_soc_24.sim/sim_1/behav/xsim/xsim.dir/bcd_updowncounter_p_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/JAEWOO_SoC/Vivado_2019/basys3_soc_24/basys3_soc_24.sim/sim_1/behav/xsim/xsim.dir/bcd_updowncounter_p_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/JAEWOO_SoC/Vivado_2019/basys3_soc_24/basys3_soc_24.sim/sim_1/behav/xsim/xsim.dir/bcd_updowncounter_p_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
