# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xadc_wiz_2/xadc_wiz_2.xdc

# XDC: imports/Downloads/Basys-3-Master.xdc

# IP: ip/xadc_wiz_2/xadc_wiz_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_2 || ORIG_REF_NAME==xadc_wiz_2} -quiet] -quiet

# XDC: ip/xadc_wiz_2/xadc_wiz_2_ooc.xdc

# XDC: ip/xadc_wiz_2/xadc_wiz_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_2 || ORIG_REF_NAME==xadc_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet
